sudo: required

language: python
python:
  - "3.6"

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get-helm-3 | bash
  - pip install chartpress==0.4.2

script:
  - helm lint dask
  - helm lint daskhub --set 'dask-gateway.gateway.auth.jupyterhub.apiToken=foo' --set 'jupyterhub.proxy.secretToken=foo'


deploy:
  - provider: script
    skip_cleanup: true
    script: ci/deploy.sh
    on:
      branch: master
      tags: true
