sudo: required

language: python
python:
  - "3.6"

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - pip install chartpress==0.4.2

script:
  - helm lint dask

deploy:
  - provider: script
    skip_cleanup: true
    script: ci/deploy.sh
    on:
      branch: master
      tags: true
