apiVersion: v1
kind: ConfigMap
metadata:
  name: daskhub-config
data:
  DASK_GATEWAY__ADDRESS: "http://proxy-public/services/dask-gateway"
  DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-{{ .Release.Name }}-dask-gateway.{{ .Release.Namespace }}:80"
  DASKHUB_JUPYTERHUB_SERVICE_GATEWAY_URL: "http://traefik-{{ .Release.Name }}-dask-gateway.{{ .Release.Namespace }}"
