name: Check Frigate

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install frigate
      - name: Check README is up to date
        run: |
          frigate gen dask > dask/README.md
          if git status --porcelain dask/README.md | grep .; then
              echo "README is out of date. Please run `frigate gen dask > dask/README.md`."
              exit 1
          fi
