# This is a GitHub workflow defining a set of jobs with a set of steps. ref:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
# This workflow package and publishes the Helm charts to Helm repository living
# inside the gh-pages branch of this git repository.
#
name: Publish charts

on:
  push:
    tags: ["*"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install chartpress==0.7.0
          curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get-helm-3 | bash
      - name: Update chart dependencies
        run: |
          helm dep update daskhub
      - name: Deploy repo
        env:
          GITHUB_TOKEN: "${{ env.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}"
          # Required for git commit:
          EMAIL: dask@dask.org
          GIT_AUTHOR_NAME: "[Dask]"
          GIT_COMMITTER_NAME: "[Dask]"
        run: |
          chartpress --tag "${GITHUB_REF#refs/*/}" --publish-chart
